[[snippets]]
  description = "Ansible diff"
  command = "ansible-playbook -i environments/<env=stg-eu-fr> playbooks/update.yml --diff --ask-vault -vvv --check -l tag_Application_<app>"
  output = ""

[[snippets]]
  description = "Terraform plan"
  command = "terraform plan -out=tfplan -var-file=../../config/<env=stg-eu-fr>.tfvars --target=<target>"
  output = ""

[[snippets]]
  description = "Ansible vault"
  command = "ansible-vault edit ./environments/<env=stg-eu-fr>/group_vars/all/secrets.yml"
  output = ""

[[snippets]]
  description = "Download BCP from S3"
  command = "record_id=<recordId=18335> && date=<date=20200909> && folder=\"${HOME}/tmp/bcp/${record_id}/bcp/${date}\" && echo \"${folder}\" && mkdir -p \"${folder}\" && for f in $(aws s3 ls s3://bioserenity-bcp-stg-eu-fr/${record_id}/bcp/${date}/ | awk '{ print $4 }'); do aws s3 cp \"s3://bioserenity-bcp-stg-eu-fr/${record_id}/bcp/${date}/${f}\" \"${folder}\"; done"
  output = ""
