# Get editor completions based on the config schema
#"$schema" = 'https://starship.rs/config-schema.json'

# General format
format = """
$time\
$hostname\
$directory\
$env_var\
$docker_context\
$package\
$helm\
$terraform\
$aws\
$custom\
$cmd_duration\
$line_break\
$jobs\
$status\
$container\
$character"""

# Settings
[cmd_duration]
min_time = 1_000
show_milliseconds = true

[directory]
truncation_length = 0
truncate_to_repo = true
style = "bold cyan"

[status]
disabled = false
symbol = '🔴 '

[time]
disabled = false
format = '[$time]($style) '

[env_var.1]
variable="GSD_REMOTE"
format="[$env_value ](#cccccc bold)"
[env_var.2]
variable="GSD_BRANCH_STATUS"
format="[$env_value ](purple bold)"
[env_var.3]
variable="GSD_ON"
format="[$env_value](purple bold)"
[env_var.4]
variable="GSD_STATUS"
format="[$env_value ]()"
[env_var.5]
variable="GSD_NOT_REPO"
format="[ ]()"
