style:
  tag:
    color: grey # text color. possible values: https://bit.ly/3gloNNI
    width_percentage: 15 # column width relative to the terminal window
    min_width: 10 # minimum column width as number of characters
  comment:
    color: white
    width_percentage: 42
    min_width: 45
  snippet:
    color: blue
